

version: "3"

services:
  db:
    container_name: pg13
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Python123}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./db_data/postgres/db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
